# Created by: Florent Thoumie <flz@freebsd.org>
# $FreeBSD$

PORTNAME=	xf86-video-scfb
PORTVERSION=	0.0.4
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ray@FreeBSD.org
COMMENT=	X.Org syscons display driver

USE_GITHUB=     yes
GH_ACCOUNT=     rayddteam
GH_PROJECT=     ${PORTNAME}
GH_TAGNAME=     bdeb3bf
GH_COMMIT=      bdeb3bf

XORG_CAT=	driver
USE_TGZ=	yes
USE_XORG=
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
