# Created by: Gleb Smirnoff <glebius@FreeBSD.org>
# $FreeBSD$

PORTNAME=	xf86-input-egalax
PORTVERSION=	0.2
PORTREVISION=	3
CATEGORIES=	x11-drivers
MASTER_SITES=	LOCAL/glebius

MAINTAINER=	glebius@FreeBSD.org
COMMENT=	eGalax touch screen input driver for X.Org

LICENSE=	BSD2CLAUSE

XORG_CAT=	driver
INSTALL_CMD=	install-strip

.include <bsd.port.post.mk>
